#!/bin/bash
# Mission Test Suite - Overview of all available mission types

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║       MOOFS MISSION TEST SUITE - Available Mission Types       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 1. WAYPOINT MISSION (test_mission.sh)"
echo "   ├─ Description: Custom point-to-point navigation"
echo "   ├─ Pattern: User-defined waypoints"
echo "   ├─ Use Cases: Delivery, inspection, custom routes"
echo "   └─ Example: 6-point box pattern with altitude changes"
echo ""

echo "🗺️  2. SURVEY MISSION (test_survey_mission.sh)"
echo "   ├─ Description: Aerial mapping with lawn-mower pattern"
echo "   ├─ Pattern: Parallel lines with configurable overlap"
echo "   ├─ Use Cases: Photogrammetry, orthophotos, agriculture"
echo "   └─ Example: 60m×40m area at 35m altitude"
echo ""

echo "🔍 3. SEARCH MISSION - Expanding Square (test_search_mission.sh)"
echo "   ├─ Description: Expanding square search pattern"
echo "   ├─ Pattern: Concentric squares from center"
echo "   ├─ Use Cases: Search & rescue, object detection"
echo "   └─ Example: 80m radius with 25m spacing"
echo ""

echo "🌀 4. SEARCH MISSION - Spiral (test_spiral_mission.sh)"
echo "   ├─ Description: Outward spiral search pattern"
echo "   ├─ Pattern: Smooth continuous spiral"
echo "   ├─ Use Cases: Thermal search, debris analysis"
echo "   └─ Example: 70m radius with 20m spacing"
echo ""

echo "🔄 5. SEQUENTIAL MISSIONS (test_sequential_missions.sh)"
echo "   ├─ Description: Multiple missions in sequence"
echo "   ├─ Pattern: 3 different waypoint patterns"
echo "   ├─ Use Cases: Test mission queuing and cooldown"
echo "   └─ Example: Square → Triangle → Diamond (5-6 min total)"
echo ""

echo "🚀 6. COMPLEX STRESS TEST (test_complex_mission.sh)"
echo "   ├─ Description: Large waypoint mission"
echo "   ├─ Pattern: 10-point spiral box pattern"
echo "   ├─ Use Cases: System stress testing"
echo "   └─ Example: 360m total distance, 4-5 minutes"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "USAGE:"
echo "  cd ~/multi_drone_ws/scripts"
echo "  ./test_<mission_type>.sh"
echo ""
echo "PREREQUISITES:"
echo "  1. SITL running:    sim_vehicle.py -v ArduCopter"
echo "  2. System launched: ros2 launch task_execution complete_system.launch.py"
echo "  3. Squadron (opt):  ros2 launch squadron_manager squadron_manager.launch.py"
echo ""
echo "MISSION PARAMETERS:"
echo ""
echo "  Waypoint Mission:"
echo "    - waypoints: [{x, y, z, yaw}, ...]"
echo "    - velocity: float (m/s)"
echo "    - acceptance_radius: float (m)"
echo ""
echo "  Survey Mission:"
echo "    - area: [{x, y}, ...] (polygon vertices)"
echo "    - altitude: float (m)"
echo "    - orientation: float (degrees, 0-180)"
echo "    - overlap: float (0.0-1.0, forward)"
echo "    - sidelap: float (0.0-1.0, side)"
echo "    - velocity: float (m/s)"
echo "    - camera: {sensor_width, sensor_height, focal_length, ...}"
echo ""
echo "  Search Mission:"
echo "    - pattern: 'expanding_square' | 'spiral' | 'creeping_line' | 'sector'"
echo "    - center: {x, y}"
echo "    - altitude: float (m)"
echo "    - radius: float (m)"
echo "    - spacing: float (m, track spacing)"
echo "    - velocity: float (m/s)"
echo "    - sensor_fov: float (degrees)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "TIPS:"
echo "  • Start with simple waypoint missions"
echo "  • Monitor battery levels (survey/search missions are longer)"
echo "  • Use ros2 topic echo to watch mission status"
echo "  • Check /drone_0/mavros/local_position/pose for real-time position"
echo "  • 5-second cooldown between sequential missions"
echo ""
echo "For more info, check: ~/multi_drone_ws/docs/"
echo "════════════════════════════════════════════════════════════════"
