#!/bin/bash

# Quick Squadron Manager Restart & Test Script
# This script helps you quickly restart squadron manager and test

set -e

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║              Squadron Manager - Quick Restart & Test                  ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

WS_DIR=~/multi_drone_ws

echo "🔧 What was fixed:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Added debug logging to state/battery/GPS callbacks"
echo "  ✅ Fixed GPS fix_type calculation (was 1, now 2+ for valid fix)"
echo "  ✅ Added diagnostic output when no drones available"
echo "  ✅ Shows battery%, GPS fix, and task status for each drone"
echo ""
echo "📋 INSTRUCTIONS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: STOP the current Squadron Manager"
echo "   → In the terminal where it's running, press Ctrl+C"
echo ""
echo "Step 2: Source the rebuilt workspace:"
echo "   → source $WS_DIR/install/setup.bash"
echo ""
echo "Step 3: RESTART Squadron Manager with DEBUG logging:"
echo "   → $WS_DIR/scripts/debug_squadron_manager.sh"
echo ""
echo "   OR use standard launch:"
echo "   → ros2 launch squadron_manager squadron_manager.launch.py num_drones:=1"
echo ""
echo "Step 4: Wait 10 seconds for callbacks to receive data"
echo "   → You should see logs like:"
echo "      [DEBUG] State callback for drone_0: connected=True..."
echo "      [DEBUG] Battery callback for drone_0: 100.0%..."
echo "      [DEBUG] GPS callback for drone_0: fix_type=2..."
echo ""
echo "Step 5: Send a test mission:"
echo "   → ./scripts/send_squadron_mission.sh 10 10 15"
echo ""
echo "Step 6: Watch for allocation success:"
echo "   → [INFO] Allocated mission squadron_test_XXX to drone_0"
echo "   → [INFO] Sending mission to drone_0 via TEE"
echo ""
echo "🎯 EXPECTED RESULTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BEFORE (what you saw):"
echo "  ❌ [ERROR] No available drones for mission"
echo "  ❌ Mission bypassed Squadron Manager, sent directly to TEE"
echo ""
echo "AFTER (what you should see now):"
echo "  ✅ [INFO] Drone drone_0 updated: state=UNKNOWN->AVAILABLE"
echo "  ✅ [INFO] Allocated mission squadron_test_XXX to drone_0"
echo "  ✅ [INFO] Sending mission to drone_0 via TEE"
echo "  ✅ Mission executed via Squadron Manager → TEE → FAL → MAVROS"
echo ""
echo "🔍 WHAT TO LOOK FOR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you still see 'No available drones', the log will now show WHY:"
echo "  Drone drone_0: state=AVAILABLE, connected=True, battery=100.0%, gps_fix=1, task=None"
echo "                                                                    ^^^^^^^^^"
echo "                                                                    Problem!"
echo ""
echo "This tells you EXACTLY what's wrong (e.g., GPS fix < 2, battery < 20%, etc.)"
echo ""
echo "💡 DEBUGGING TIPS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "• If state stays UNKNOWN:"
echo "    → State callback not firing - check MAVROS connection"
echo ""
echo "• If battery shows 0.0%:"
echo "    → Battery callback not firing - check /drone_0/mavros/battery topic"
echo ""
echo "• If gps_fix < 2:"
echo "    → GPS callback not firing OR fix calculation wrong"
echo "    → Check: ros2 topic echo /drone_0/mavros/global_position/global --once"
echo ""
echo "• If task != None:"
echo "    → Drone thinks it has a task - wait for task to complete or reset"
echo ""
echo "Ready? Follow the steps above! 🚀"
echo ""
