# MAVROS Timesync Configuration
# Reduces timesync rate to prevent RTT spikes and stabilize TF timing

/**:
  ros__parameters:
    # Timesync plugin configuration
    timesync_rate: 2.0        # Reduced from default 10Hz to 2Hz
    timesync_avg_alpha: 0.6   # Filter constant for averaging
    timesync_avg_beta: 0.9    # Filter constant for variance
    
    # Connection timeouts
    conn_timeout: 30.0        # Connection timeout in seconds
    conn_heartbeat: 5.0       # Heartbeat rate
    
    # System configuration
    startup_px4_usb_quirk: false
    system_id: 1
    component_id: 1
    
    # Reduce message spam
    conn_system_time: true
    conn_timesync: true
