/**:
  ros__parameters:
    # Connection to ArduPilot SITL
    fcu_url: "udp://:14555@127.0.0.1:14550"
    gcs_url: ""
    tgt_system: 1
    tgt_component: 1
    fcu_protocol: "v2.0"
    
    # Plugin configuration
    plugin_allowlist:
      - 'sys_*'
      - 'global_position'
      - 'local_position'
      - 'setpoint_*'
      - 'imu'
      - 'altitude'
      - 'param'
      - 'command'
    
    # Time sync
    conn:
      timesync_rate: 10.0
      system_time_rate: 1.0
      heartbeat_rate: 1.0
      timeout: 10.0
    
    # Position publishing
    local_position:
      frame_id: "map"
      tf:
        send: true
        frame_id: "map"
        child_frame_id: "base_link"
        rate_limit: 50.0
    
    global_position:
      frame_id: "earth"
      
    # Setpoint configuration  
    setpoint_position:
      mav_frame: 1  # LOCAL_NED frame
      
    setpoint_velocity:
      mav_frame: 8  # BODY_NED frame