# motion_controller_config.yaml
/**:
  ros__parameters:
    # Controller plugin configuration
    controller_plugin_name: "pid_speed_controller::Plugin"
    cmd_freq: 30.0
    info_freq: 10.0
    
    # Motion reference configuration
    motion_reference_adder_plugin_name: "position_motion"
    
    # PID Controller parameters
    position_control:
      p: [1.0, 1.0, 1.0]  # X, Y, Z
      i: [0.0, 0.0, 0.0]
      d: [0.5, 0.5, 0.5]
      max_output: [5.0, 5.0, 2.0]  # Max velocity commands
      
    velocity_control:
      p: [1.0, 1.0, 1.0]
      i: [0.0, 0.0, 0.0]
      d: [0.0, 0.0, 0.0]
      
    yaw_control:
      p: 1.0
      i: 0.0
      d: 0.0
      max_output: 0.5  # Max yaw rate
      
    # Limits
    max_velocity_xy: 5.0
    max_velocity_z: 2.0
    max_yaw_rate: 0.5