/**:
  ros__parameters:
    max_thrust: 15.0
    min_thrust: 0.0
    external_odom: true
    # TF timing parameters
    tf_timeout_threshold: 0.15
    tf_timeout: 0.2
    tf_tolerance: 0.1
    tf_buffer_size: 20.0
    # Info frequency
    info_freq: 10.0
    cmd_freq: 50.0